services:
  gita-assistant:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - APP_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 